LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CLK_DIV IS
    PORT (
        CLK : IN STD_LOGIC;
        PIXEL_CLK : OUT STD_LOGIC
    );
END ENTITY;

ARCHITECTURE BEHAVIORAL OF CLK_DIV IS
    SIGNAL CLK25, CLK50 : STD_LOGIC := '0';
BEGIN
    PIXEL_CLK <= CLK25;
    CLK50_PROC : PROCESS (CLK)
    BEGIN
        IF (CLK'event AND CLK = '1') THEN
            CLK50 <= NOT CLK50;
        END IF;
    END PROCESS;

    CLK25_PROC : PROCESS (CLK50)
    BEGIN
        IF (CLK50'event AND CLK50 = '1') THEN
            CLK25 <= NOT CLK25;
        END IF;
    END PROCESS;
END BEHAVIORAL;