# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/col215/hw3_2/hw3_2.srcs/sources_1/ip/filter_rom/filter_rom.xci
# IP: The module: 'filter_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/col215/hw3_2/hw3_2.gen/sources_1/ip/filter_rom/filter_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/col215/hw3_2/hw3_2.srcs/sources_1/ip/filter_rom/filter_rom.xci
# IP: The module: 'filter_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/col215/hw3_2/hw3_2.gen/sources_1/ip/filter_rom/filter_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
