# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/btech/tt1211139/col215/assi_02/assi_02.srcs/sources_1/ip/ram/ram.xci
# IP: The module: 'ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/btech/tt1211139/col215/assi_02/assi_02.srcs/sources_1/ip/ram/ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/btech/tt1211139/col215/assi_02/assi_02.srcs/sources_1/ip/ram/ram.xci
# IP: The module: 'ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/btech/tt1211139/col215/assi_02/assi_02.srcs/sources_1/ip/ram/ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
